version: "3.9"

volumes:
  redis-data:

services:
  ui:
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    ports:
      - "3330:3000"

  user-svc:
    build:
      context: ./user-service
      target: dev
    volumes:
      - ./user-svc/src:/app/src
      - ./user-svc/public:/app/public
    ports:
      - "3330:3000"